### ISSUE TITLE
Question: Environment menu

### ISSUE THREAD

**Issue by tallguyjenks** [lusignan/Nord-RStudio#1]
i have a theme of my own ive been developing [Gruvboxr](https://github.com/tallguyjenks/gruvboxr) but when ever i turn the theme on the environment menu is not the color it should be, the background is light not dark. 

what is the segment of the ace theme code you're using for the environment menu background? i tried to inspect the elements and do direct CSS selection but i cant seem to get it

**Comment by lusignan** [comment]
I think that these are what you're after. The hex codes are what I used in mine.

Main pane of the menu:
`.dialogMiddleCenter {
  background: #434C5E !important;
  color: #ECEFF4;
}`

Background for most of the menu:
`.GD15MCFCGP .gwt-TabLayoutPanelContentContainer, .GD15MCFCOID, .GD15MCFCNLD {
    background: #434C5E !important;
    border: 1px solid #3B4252;
    border-radius: 3px;
}`

Dropdown menus (to select the theme, font, etc.):
`select {
    font-size: 11px;
    text-indent: 0.1em;
    background-color: #3B4252 !important;
    color: #ECEFF4;
    border: none !important;
}`

Buttons in the menu:
`.rstudio-themes-flat button.gwt-Button-DialogAction>table:first-child, .rstudio-themes-flat button.GD15MCFCB1>table:first-child, .rstudio-themes-flat button.GD15MCFCH1>table:first-child, button.GD15MCFCB1 table tbody {
    border-radius: 3px !important;
    background: #3B4252 !important;
    color: #ECEFF4 !important;
    border: none !important;
    box-shadow: none !important;
}`

I've also added more comments to my code so it's easier to tell what each section does, if you'd like to use it as a reference.

I recommend using Atom with the Pigments package to edit your rstheme. It highlights each color code with the color it translates to so you can quickly see what doesn't belong.

**Comment by tallguyjenks** [comment]
thank you for the detailed response! i appreciate it very much!
